### ISSUE TITLE
Hanging on both Chrome and Firefox

### ISSUE THREAD

**Issue by elewis33** [jd-m3/keep-instance-alive#2]
I've tried using both the chromedriver and geckodriver installations, and the code is hanging in  different places with each. 

I'm on a Macbook Pro with Mojave 10.14.6 and the latest version of both browsers. 

When using Firefox it hangs at the point where the email address is entered into the username field and the button click happens. 

With Chrome it never seems to redirect to the login page. 

I've added a bunch of console.log() statements to track each step of the process, and was able to verify where it hangs by watching each step in the process. 

Is this still working for you @jd-m3? 

It looks like you've accommodated the new login page processing that they use on the developer site, but something isn't happy. I've looked into the page source and all of the fields and button names seem to be correct, but no joy for me. Any ideas?

**Comment by jd-m3** [comment]
Hi, I still use this and is running everyday through a CRON job. Can you provide an error log so I can track what can be the problem?

**Comment by elewis33** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webdriver' ]
2 info using npm@6.2.0
3 info using node@v10.8.0
4 verbose run-script [ 'prewebdriver', 'webdriver', 'postwebdriver' ]
5 info lifecycle keep-instance-alive@1.0.0~prewebdriver: keep-instance-alive@1.0.0
6 info lifecycle keep-instance-alive@1.0.0~webdriver: keep-instance-alive@1.0.0
7 verbose lifecycle keep-instance-alive@1.0.0~webdriver: unsafe-perm in lifecycle true
8 verbose lifecycle keep-instance-alive@1.0.0~webdriver: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/elewis/Google Drive/Projects/js/keep-instance-alive/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/elewis/Google Drive/Projects/js/keep-instance-alive/node_modules/.bin:/Users/elewis/anaconda3/bin:/Users/elewis/.pyenv/shims:/Users/elewis/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/opt/local/bin:/opt/local/sbin:/usr/local/share/python:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/opt/oracle/instantclient_11_2:/usr/local/share/npm/bin:/usr/local/mongodb/bin:/usr/local/share/npm/lib/node_modules/bower/bin:/usr/local/opt/rmtoo-23/bin:/usr/local/lib/python2.7/site-packages
9 verbose lifecycle keep-instance-alive@1.0.0~webdriver: CWD: /Users/elewis/Google Drive/Projects/js/keep-instance-alive
10 silly lifecycle keep-instance-alive@1.0.0~webdriver: Args: [ '-c',
10 silly lifecycle   'java -jar selenium-server/selenium-server-standalone-3.13.0.jar' ]
11 silly lifecycle keep-instance-alive@1.0.0~webdriver: Returned: code: 143  signal: null
12 info lifecycle keep-instance-alive@1.0.0~webdriver: Failed to exec webdriver script
13 verbose stack Error: keep-instance-alive@1.0.0 webdriver: `java -jar selenium-server/selenium-server-standalone-3.13.0.jar`
13 verbose stack Exit status 143
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
14 verbose pkgid keep-instance-alive@1.0.0
15 verbose cwd /Users/elewis/Google Drive/Projects/js/keep-instance-alive
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/10.8.0/bin/node" "/usr/local/bin/npm" "run" "webdriver"
18 verbose node v10.8.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 143
22 error keep-instance-alive@1.0.0 webdriver: `java -jar selenium-server/selenium-server-standalone-3.13.0.jar`
22 error Exit status 143
23 error Failed at the keep-instance-alive@1.0.0 webdriver script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 143, true ]

**Comment by jd-m3** [comment]
Sorry if it took much time for me to respond as I have my day job. I pushed a revision (593305cca9bf3b49741e1eb43a4cccd4912a6596) that extends element lookup time when waking an instance. Maybe this will fix your problem.

**Comment by jd-m3** [comment]
See #3 for more details. I'll close this for now
